stages:
  - download_caddy
  - build_docker
build:caddy:
  stage: download_caddy
  image: alpine:3.5
  variables:
    ARCHITECTURE: "amd64"
    PLUGINS: ""
  script:
    - apk add --no-cache openssh-client tar curl
    - curl --silent --show-error --fail --location -k -o caddy_linux_amd64_custom.tar.gz "https://caddyserver.com/download/build?os=linux&arch=${ARCHITECTURE}&features=${PLUGINS}"
    - tar --no-same-owner -zxvf caddy_linux_amd64_custom.tar.gz caddy
    - chmod 0755 caddy
    - ./caddy -version
  artifacts:
    when: on_success
    expire_in: 3 days
    paths:
      - caddy

build:docker:
  image: docker:latest
  stage: build_docker
  variables:
    PROJECT_NAME: "caddy"
  dependencies:
    - build:caddy
  services:
    - docker:dind
  script:
    - docker info
    - docker login -u$DOCKER_HUB_USER -p$DOCKER_HUB_PASSWORD
    - docker build -t aohorodnyk/${PROJECT_NAME}:$CI_BUILD_REF_NAME .
    - docker push aohorodnyk/${PROJECT_NAME}:$CI_BUILD_REF_NAME
  except:
    - master

build:docker:latest:
  image: docker:latest
  stage: build_docker
  variables:
    PROJECT_NAME: "caddy"
  dependencies:
    - build:caddy
  services:
    - docker:dind
  script:
    - docker info
    - docker login -u$DOCKER_HUB_USER -p$DOCKER_HUB_PASSWORD
    - docker build -t aohorodnyk/${PROJECT_NAME}:latest .
    - docker push aohorodnyk/${PROJECT_NAME}:latest
    - DOCKER_VERSION_FULL=$(./caddy --version | grep -o '[0-9\.]\+' | head -1)
    - docker tag aohorodnyk/${PROJECT_NAME}:latest aohorodnyk/${PROJECT_NAME}:${DOCKER_VERSION_FULL}
    - docker push aohorodnyk/${PROJECT_NAME}:${DOCKER_VERSION_FULL}
    - DOCKER_VERSION_MINOR=$(./caddy --version | grep -o '[0-9]\+\.[0-9]\+' | head -1)
    - docker tag aohorodnyk/${PROJECT_NAME}:latest aohorodnyk/${PROJECT_NAME}:${DOCKER_VERSION_MINOR}
    - docker push aohorodnyk/${PROJECT_NAME}:${DOCKER_VERSION_MINOR}
    - DOCKER_VERSION_MAJOR=$(./caddy --version | grep -o '[0-9]\+' | head -1)
    - docker tag aohorodnyk/${PROJECT_NAME}:latest aohorodnyk/${PROJECT_NAME}:${DOCKER_VERSION_MAJOR}
    - docker push aohorodnyk/${PROJECT_NAME}:${DOCKER_VERSION_MAJOR}
