stages:
  - download_caddy
  # - build_docker
build:caddy:
  stage: download_caddy
  image: alpine:3.5
  variables:
    ARCHITECTURE: "amd64"
    PLUGINS: ""
  script:
    - apk add --no-cache openssh-client tar curl
    - curl --silent --show-error --fail --location \
        --header "Accept: application/tar+gzip, application/x-gzip, application/octet-stream" -o - \
        "https://caddyserver.com/download/build?os=linux&arch=${ARCHITECTURE}&features=${PLUGINS}" \
      | tar --no-same-owner -xz caddy
    - chmod 0755 caddy
    - caddy -version
  artifacts:
    when: on_success
    expire_in: 3 days
    paths:
      - caddy
# build:docker:
#   stage: build_docker
#   dependencies:
#     - build:caddy
#   image: docker:latest
#   services:
#     - docker:dind
#   script:
#     - docker info
#     - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.c.discort.com
#     - docker build -t registry.c.discort.com/advanced-british-education/backend:test .
#     - docker push registry.c.discort.com/advanced-british-education/backend:test
