stages:
  - build_docker

build:docker:latest:
  image: docker:latest
  stage: build_docker
  variables:
    PROJECT_NAME: "caddy"
  services:
    - docker:dind
  script:
    - docker build -t aohorodnyk/${PROJECT_NAME}:latest .
    - DOCKER_VERSION_FULL=$(docker run --rm -i aohorodnyk/${PROJECT_NAME}:latest caddy --version | grep -o '[0-9\.]\+' | head -1)
    - DOCKER_VERSION_MINOR=$(echo $DOCKER_VERSION_FULL | grep -o '[0-9]\+\.[0-9]\+' | head -1)
    - DOCKER_VERSION_MAJOR=$(echo $DOCKER_VERSION_MINOR | grep -o '[0-9]\+' | head -1)
    - docker info
    - docker login -u$DOCKER_HUB_USER -p$DOCKER_HUB_PASSWORD
    - docker push aohorodnyk/${PROJECT_NAME}:latest
    - docker tag aohorodnyk/${PROJECT_NAME}:latest aohorodnyk/${PROJECT_NAME}:${DOCKER_VERSION_FULL}
    - docker push aohorodnyk/${PROJECT_NAME}:${DOCKER_VERSION_FULL}
    - docker tag aohorodnyk/${PROJECT_NAME}:latest aohorodnyk/${PROJECT_NAME}:${DOCKER_VERSION_MINOR}
    - docker push aohorodnyk/${PROJECT_NAME}:${DOCKER_VERSION_MINOR}
    - docker tag aohorodnyk/${PROJECT_NAME}:latest aohorodnyk/${PROJECT_NAME}:${DOCKER_VERSION_MAJOR}
    - docker push aohorodnyk/${PROJECT_NAME}:${DOCKER_VERSION_MAJOR}
  only:
    - master
  tags:
    - docker
